name: Run Tests and check Version

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
  version-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch current and previuos

      - name: Check versions
        run: chmod u+x check_versions.sh && ./check_versions.sh

      - name: Version check passed
        run: |
          echo "🎉 Version check passed! Ready to proceed with deployment or further steps."
